# Configurações do banco de dados
database:
  # Tipo de banco de dados: MySQL
  tipo: 'MySQL'
  
  # Configurações do MySQL
  mysql:
    # Utilizar HikariCP para conexões
    hikari: false
    
    # Utilizar driver da MariaDB
    mariadb: false
    
    # Configurações de conexão
    host: 'localhost'
    porta: '3306'
    nome: 'server'
    usuario: 'root'
    senha: ''