# Informações do plugin
author: LuizOtimizador
name: ${project.artifactId}
version: ${project.version}

# Dependências obrigatórias
depend: 
  - ProtocolLib
  - PlaceholderAPI

# Classe principal do plugin
main: ${main-bukkit}