# ========================================
# CONFIGURAÇÃO PRINCIPAL DO PLUGIN
# ========================================

# Configurações do banco de dados
database:
  # Tipos de bancos de dados disponíveis: MongoDB, MySQL
  tipo: 'MySQL'
  
  # Configurações do MySQL
  mysql:
    # Utilizar HikariCP para conexões
    hikari: false
    
    # Utilizar driver da MariaDB
    mariadb: false
    
    # Configurações de conexão
    host: 'localhost'
    porta: '3306'
    nome: 'server'
    usuario: 'root'
    senha: ''
  
  # Configurações do MongoDB
  mongodb:
    # URL de acesso ao MongoDB
    # Formato: mongodb://usuario:senha@host:porta/database
    # Documentação: https://docs.mongodb.com/manual/reference/connection-string/
    url: ''
